# Generated by Django 2.2.19 on 2021-06-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20210525_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarystatisticdaily',
            old_name='distance_from_home',
            new_name='distance_from_home_maximum',
        ),
    ]
